- name: OSPF
  hosts: all
  become: true
  vars_files:
    - defaults/main.yml

  tasks:
#  - name: Install base tools
#    ansible.builtin.apt:
#      name:
#        - vim
#        - traceroute
#        - tcpdump
#        - net-tools
#      state: present
#      update_cache: true
#
#  - name: Disable ufw service
#    ansible.builtin.systemd:
#      name: ufw
#      state: stopped
#      enabled: false
#
#  - name: Add gpg frrouting.org
#    ansible.builtin.apt_key:
#     url: "https://deb.frrouting.org/frr/keys.asc"
#     state: present
#
#  - name: Add frr repo
#    ansible.builtin.apt_repository:
#     repo: 'deb https://deb.frrouting.org/frr {{ ansible_distribution_release }} frr-stable'
#     state: present
#
#  - name: Install FRR packages
#    ansible.builtin.apt:
#      name:
#        - frr
#        - frr-pythontools
#      state: present
#      update_cache: true
#  
#  - name: Set up forward packages across routers
#    ansible.posix.sysctl:
#      name: net.ipv4.conf.all.forwarding
#      value: '1'
#      state: present
#  
#  - name: Base set up OSPF
#    ansible.builtin.template:
#      src: daemons
#      dest: /etc/frr/daemons
#      owner: frr
#      group: frr
#      mode: 0640
#  
#  - name: Set up OSPF
#    ansible.builtin.template:
#      src: frr.conf.j2
#      dest: /etc/frr/frr.conf
#      owner: frr
#      group: frr
#      mode: 0640
#  
#  - name: restart FRR
#    ansible.builtin.systemd:
#      name: frr
#      state: restarted
#      enabled: true
#
#  - name: set up asynchronous routing
#    ansible.posix.sysctl:
#      name: net.ipv4.conf.all.rp_filter
#      value: '0'
#      state: present    

  - name: set up OSPF
    ansible.builtin.template:
      src: frr.conf.j2
      dest: /etc/frr/frr.conf
      owner: frr
      group: frr
      mode: 0640
    tags:
      - setup_ospf

  - name: restart FRR
    ansible.builtin.systemd:
      name: frr
      state: restarted
      enabled: true
    tags:
      - setup_ospf

